### ISSUE TITLE
完全帰納法の説明について

### ISSUE THREAD

**Issue by iehality** [lean-ja/tactic-cheatsheet#104]
https://lean-ja.github.io/tactic-cheatsheet/Tactic/Induction.html#%E5%AE%8C%E5%85%A8%E5%B8%B0%E7%B4%8D%E6%B3%95 において、

> 強い帰納法とは， たとえば
> - `P (0)`を示す
> - `(∀ k < n, P (k)) → P (n)`を示す
> - したがって ∀ n, P (n) である

とありますが、「`P (0)`を示す」の部分は二番目の条件より成り立つので不要ではないでしょうか？

**Comment by Seasawher** [comment]
コメントありがとうございます．確かに不要ですね．

```lean
import Mathlib.Tactic

variable {P : Nat → Prop}

example (h : ∀ n, (∀ k < n, P k) → P n) : P 0 := by
  specialize h 0
  simpa using h
```
