### ISSUE TITLE
add `import Mathlib.Data.Set.Basic` to the start of #check

### ISSUE THREAD

**Issue by Eric-Song-Nop** [lean-ja/tactic-cheatsheet#145]
in \#check, there is one example with `#check ({1, 2, 3} : Set Nat)`, while `Set` is not a standard lean4 type, it is defined by Mathlib, thus when opening this code with live.lean playground, there would be an error.

I think you might want to either remove this example or add the import at the start.

**Comment by Eric-Song-Nop** [comment]
I just realized that this code in the source while not in the webpage, maybe you want to move it after the first comment block in lean code

**Comment by Seasawher** [comment]
Thanks for your comment.

Indeed, it is confusing to see that the necessary import statements are hidden by `--#`. Since `Set` is not needed as a concrete example of `#check`, it seems more prospective to simply delete it.
