### ISSUE TITLE
Theorem Proving にあるタクティクスのうち載っていないもの

### ISSUE THREAD

**Issue by LumaKernel** [lean-ja/tactic-cheatsheet#32]
[Theorem Proving](https://lean-lang.org/theorem_proving_in_lean4/tactics.html) をちょうど読んでいて，そこで触れられているもので載っていないものを探してみました

- [ ] let
- [ ] intros (introでも特に触れられていない)
- [ ] rename_i
- [ ] revert
- [ ] match
- [ ] simp_arith
- [ ] generalize

コンビネータ寄り？
- [ ] #35
- [ ] #36
- [ ] all_goals/any_goals

コンビネータも入れたい？（別 Issue にすべきであればそうします，セクションをそもそも分けたほうがいいかもしれません)
- [ ] `;`
- [ ] `<;>`
- [ ] first| tac| ...

また，以下細かい点

- [ ] (目次に) rwはあるがrewriteはない
- [ ] (目次に) sorryはあるがadmitはない

---

あくまでも good first issue として役立てばと思い列挙させていただきました，私も取り組めそうなとこから触ってみようかなと思います

**Comment by Seasawher** [comment]
コメントありがとうございます．

このタクティクリストは数学やアルゴリズムの検証などで証明を書く際に役立つタクティクをまとめておきたいというコンセプトで運営しており，特にチートシート（早見表）であって教科書ではありません．

したがって，[Theorem Proving in Lean 4](https://aconite-ac.github.io/theorem_proving_in_lean4_ja/) などのチュートリアルで紹介されたタクティクを全部まとめようとは思っていません．（TPiL はリンク集に追加しておくべきですね．後で追加しておきます）

[Lean phrasebook](https://docs.google.com/spreadsheets/d/1Gsn5al4hlpNc_xKoXdU6XGmMyLiX4q-LFesFVsMlANo/edit#gid=0) のような早見表にコード例を足して多少丁寧に解説したようなものを目指しています．

**Comment by Seasawher** [comment]
個別にコメントすると，

* `let` は基本的過ぎるので扱いません. `set` との違いは述べているので十分だと思います．
* `intros` は，`intro` で代用できるので放置していました．どちらかというと `intro` を使うべきだと思うので，紹介する必要はないと考えています．
* `rename_i` は，inaccessible names に名前を付けられる便利なタクティクですが，そもそもローカルコンテキストの必要な命題がアクセス不能になることは回避すべきなので，紹介していませんでした．紹介しても良いと思いますが，優先度は低いです．やるとしたら `rename` と一緒に紹介したいと思います．
* `revert` は，これが有用になるケースが思いつかなかったので紹介していません．
* `match` は当たり前だと思ってしまっていて，盲点でした．紹介してもいいかもしれません．
* `simp_arith` はちょっとマニアックな気もしますが，有用になるコード例があれば紹介します．
* `generalize` も役に立つコード例があればという感じです．

* `repeat` と `try` は，コード例の中で使っているのに紹介していませんでしたね…．紹介すべきだと思います．
* `all_goals/any_goals` は，便利なときもあるので紹介したいですね．役に立つコード例があれば紹介できます．
* コンビネータは紹介しません．それは TPiL などに投げた方が良いと思います．
* 「rwはあるがrewriteはない」意図的なものです．`rw` の方が短いですし，これだけで足ります．
* 「sorryはあるがadmitはない」使い分けると便利になることがあると感じなかったのでそうしています．使い分けるべきケースがあれば紹介します．

**Comment by LumaKernel** [comment]
ありがとうございます．網羅することが目的でないのは単純に読んでいませんでした．

一つ一つ返していただきありがとうございます．単純にヘビーユーザーの方の感覚が分かって助かります．

そうであれば，確かに，基本的にはそれを必要とする状況がないか，という点で有用なものに絞ったほうが良さそうですね．一応，逆引きしたい状況は（チュートリアルが状況別にそれらを紹介した，という点もあって，）あるだろうという考えで開いたissueではありますが，実践レベルでそれぞれどうか，どのような例があるか，というのは現時点で私は持っておらず，用意していく必要があると思います．

その上でこの

一点，revertについて，revertを知っていないと，これができなくてどうしようもないのではないか，とも感じるのであってもいいのではないかなとも感じました．

例えば，

**Comment by Seasawher** [comment]
> 確かに，基本的にはそれを必要とする状況がないか，という点で有用なものに絞ったほうが良さそうですね．

refine さえあれば apply も exact も constructor も代用できてしまいますが，実際にはすべて紹介しています．それは，「短く書けるから嬉しい」とか，「専用のタクティクがあると見やすい」とかそういう理由で紹介しているわけです．「この操作がやりたい」という状況があれば紹介してもいいと思います．

「revert が有用になるケースが思いつかない」と言いましたが，いただいた例を見て，確かに一度 intro したものを戻そうと思うと revert せざるを得ないなと思いました．mathlib でも結構使われているようですし，私が知らなかっただけで有用なのかもしれません．

> その上でこのissueは閉じたほうがよろしいでしょうか？

TPiL にあるタクティクを網羅すべきかという議論は終わったかと思いますので，クローズしようと思います．
