### ISSUE TITLE
早見表なのか辞書なのか

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/tactic-cheatsheet#40]
当初は「便利なタクティクを集めて，早見表を作る」のが目的でしたが，紹介するタクティクが多くなってきて辞書のようになりつつあります．早見表としての利便性は確保できているのでしょうか…？

個人的には日本語検索が可能になった時点で十分だと感じていましたが，まだ足りないかもしれません．

Lean 初心者の意見を聞きたいところです．

**Comment by Seasawher** [comment]
早見表としてのインターフェースの話は #39 に一本化する

**Comment by LumaKernel** [comment]
> 日本語検索が可能になった

@Seasawher 
すみません，これはどこかのドキュメントにその機能が入ったということでしょうか？
それとも，こちらのチートシートにより日本語検索ができるようになった，ということでしょうか？

**Comment by Seasawher** [comment]
@LumaKernel カスタマイズしないと mdbook の検索機能では日本語検索ができません．このチートシートでは，追加のカスタマイズを入れることにより日本語検索ができるようにしてあります．それを指しています．

**Comment by LumaKernel** [comment]
@Seasawher なるほど、ありがとうございます。
